services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_DB_USER} -d $${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "./wait-for-db.sh db python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env

  celery_worker:
    build: .
    command: bash -c "./wait-for-db.sh db celery -A alx_backend_caching_property_listings worker --loglevel=info"
    volumes:
      - .:/app
    env_file: .env

  celery_beat:
    build: .
    command: bash -c "./wait-for-db.sh db celery -A alx_backend_caching_property_listings beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    env_file: .env

volumes:
  pgdata:
